//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ZooCam.rc
//
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDC_WINDOWSPROJECT1             109
#define IDR_MAINFRAME                   128
#define IDB_LOGO                        135
#define IDB_YELLOW_LED                  139
#define IDB_RED_LED                     140
#define IDB_GREEN_LED                   141
#define IDB_GRAY_LED                    142
#define IDV_CURRENT                     1000
#define IDV_VOLTAGE                     1001
#define IDB_CURRENT_ON                  1002
#define IDT_CURRENT                     1003
#define IDB_CURRENT_OFF                 1004
#define ID_LED                          1005
#define IDT_VOLTAGE                     1006
#define IDT_LEVELS                      1007
#define IDT_STATUS                      1009
#define IDB_SET_I                       1010
#define IDB_SET_V                       1011
#define IDC_CONNECT                     1015
#define IDC_B0                          1016
#define IDC_B1                          1017
#define IDC_B2                          1018
#define IDC_B3                          1019
#define IDC_B4                          1020
#define IDT_SRQ                         1021
#define IDB_STATUS_UPDATE               1022
#define IDC_STATUS_ON                   1023
#define IDB_SAVE                        1998
#define IDT_COMPILE_VERSION             1999
#define IDC_STATIC_ABOUT_COMPANY        2000
#define IDC_STATIC_ABOUT_APPNAME        2001
#define IDC_GPIB                        2002
#define IDC_DISPLAY                     2003
#define IDC_LIVE                        2004
#define IDB_CAPTURE                     2006
#define IDB_TRIGGER                     2006
#define IDB_SAVE_BURST                  2007
#define IDB_SAVE_PARAMETERS             2008
#define IDB_LOAD_PARAMETERS             2009
#define IDC_CAMERA_LIST                 2010
#define IDC_CAMERA_MODES                2011
#define IDB_CAMERA_DETAILS              2012
#define IDT_CAMERA_MANUFACTURER         2013
#define IDB_CAMERA_DISCONNECT           2013
#define IDT_CAMERA_MODEL                2014
#define IDT_CAMERA_SERIAL_NO            2015
#define IDT_CAMERA_ID                   2016
#define IDT_CAMERA_IMAGE_SIZE           2017
#define IDT_CAMERA_PIXEL_PITCH          2018
#define IDT_CAMERA_VERSION              2019
#define IDT_CAMERA_SENSOR_SIZE          2019
#define IDT_CAMERA_DATE                 2020
#define IDT_CAMERA_COLOR_MODE           2021
#define IDT_PIXEL_CLOCK_MIN             2022
#define IDS_FRAMERATE                   2022
#define IDT_PIXEL_CLOCK_DEFAULT         2023
#define IDV_FRAMERATE                   2023
#define IDT_PIXEL_CLOCK_CURRENT         2024
#define IDT_ACTUALFRAMERATE             2024
#define IDS_EXPOSURE_TIME               2025
#define IDT_PIXEL_CLOCK_MAX             2025
#define IDV_EXPOSURE_TIME               2026
#define IDT_PIXEL_CLOCK_INC             2026
#define IDS_GAMMA                       2027
#define IDT_CAMERA_NAME                 2027
#define IDV_GAMMA                       2028
#define IDB_GAMMA_NEUTRAL               2029
#define IDT_CAMERA_BIT_DEPTH            2029
#define IDR_COLOR_DISABLE               2030
#define IDR_COLOR_ENABLE                2031
#define IDR_COLOR_BG40                  2032
#define IDR_COLOR_HQ                    2033
#define IDR_COLOR_AUTO_IR               2034
#define IDV_COLOR_CORRECT_FACTOR        2035
#define IDG_VERT_PROFILE                2036
#define IDT_RED_SATURATE                2037
#define IDT_GREEN_SATURATE              2038
#define IDT_BLUE_SATURATE               2039
#define IDS_MASTER_GAIN                 2040
#define IDV_MASTER_GAIN                 2041
#define IDS_RED_GAIN                    2042
#define IDV_RED_GAIN                    2043
#define IDS_GREEN_GAIN                  2044
#define IDV_GREEN_GAIN                  2045
#define IDS_BLUE_GAIN                   2046
#define IDV_BLUE_GAIN                   2047
#define IDG_HORZ_PROFILE                2048
#define IDG_HISTOGRAMS                  2049
#define IDR_EXPOSURE_100US              2050
#define IDR_EXPOSURE_1MS                2051
#define IDR_EXPOSURE_10MS               2052
#define IDR_EXPOSURE_100MS              2053
#define IDT_MIN_EXPOSURE                2054
#define IDT_MID_EXPOSURE                2055
#define IDT_MAX_EXPOSURE                2056
#define IDB_RESET_CURSOR                2057
#define IDC_SHOW_INTENSITY              2058
#define IDC_SHOW_RGB                    2059
#define IDC_ENABLE_DCX_ERRORS           2060
#define IDC_FULL_WIDTH_CURSOR           2061
#define IDB_AUTO_EXPOSURE               2062
#define IDV_CURSOR_X_PIXEL              2063
#define IDV_CURSOR_Y_PIXEL              2064
#define IDV_RING_SIZE                   2065
#define IDT_FRAME_COUNT                 2066
#define IDT_FRAME_VALID                 2067
#define IDV_PIXEL_CLOCK_SET             2067
#define IDB_PIXEL_CLOCK_SET             2068
#define IDV_CURRENT_FRAME               2068
#define IDT_SHARPNESS                   2069
#define IDB_SHARPNESS_DIALOG            2070
#define IDB_LED_CONFIGURE               2071
#define IDV_COM_PORT                    2072
#define IDC_TRACK_CENTROID              2072
#define IDC_ENABLE                      2073
#define IDV_TRIG_COUNT                  2073
#define IDV_LED_ON                      2074
#define IDV_FRAMERATE_LIMIT             2074
#define IDV_LED_OFF                     2075
#define IDR_LED_OFF                     2076
#define IDR_LED_ON                      2077
#define IDR_LED_TOGGLE                  2078
#define IDG_FOCUS_GRAPH                 2079
#define IDR_TIME_SEQUENCE               2080
#define IDR_FOCUS_SWEEP                 2081
#define IDC_PAUSE                       2082
#define IDB_CLEAR_FOCUS_GRAPH           2083
#define IDT_EST_FOCUS                   2084
#define IDB_SET_EST_FOCUS               2085
#define IDB_PREV_FRAME                  2087
#define IDB_NEXT_FRAME                  2088
#define IDB_BURST_ARM                   2090
#define IDB_LED_OFF                     2091
#define IDB_LED_ON                      2092
#define IDG_LED                         2093
#define IDT_CAMERA_EXPOSE_MIN           2094
#define IDT_CAMERA_EXPOSE_MAX           2095
#define IDT_CAMERA_FPS_MIN              2096
#define IDT_CAMERA_FPS_MAX              2097
#define IDT_CAMERA_GAIN_MIN             2098
#define IDT_CAMERA_GAIN_MAX             2099
#define IDT_CAMERA_FIRMWARE             2100
#define IDG_COLOR_CORRECTION            2101
#define IDS_TEXT_0                      2102
#define IDC_SHOW_SUM                    2103
#define IDB_RESET_GAINS_RGB             2104
#define IDT_IMAGE_INFO                  2105
#define IDR_TRIG_FREERUN                2106
#define IDR_TRIG_SOFTWARE               2107
#define IDR_TRIG_EXTERNAL               2108
#define IDR_TRIG_SS                     2109
#define IDR_TRIG_BURST                  2110
#define IDT_TRIG_COUNT                  2111
#define IDR_IMAGE_BMP                   2112
#define IDR_IMAGE_RAW                   2113
#define IDR_IMAGE_JPG                   2114
#define IDR_IMAGE_PNG                   2115
#define IDC_ARM                         2116
#define IDC_FLOAT                       2117
#define IDT_FPS_MAX                     2119
#define IDT_FPS_MIN                     2120
#define IDR_TRIG_POS                    2121
#define IDR_TRIG_NEG                    2122
#define IDB_DEBUG                       2123
#define IDB_RESET_FRAME                 2124
#define IDB_RESET_RING                  2124
#define IDC_AUTOSAVE                    2125
#define IDT_AUTOSAVE_FNAME              2126
#define IDV_TEMPLATE                    2127
#define IDB_ID_CONFIG                   2127
#define IDV_NEXT_INDEX                  2128
#define IDV_DIRECTORY                   2129
#define IDB_BROWSE                      2130
#define IDB_ROI                         2131
#define IDB_FULL_FRAME                  2131
#define IDT_ROI_INFO                    2132
#define IDB_RES_1                       2132
#define IDB_RES_2                       2133
#define IDB_RES_3                       2134
#define IDB_RES_4                       2135
#define IDB_RES_5                       2136
#define IDB_RES_6                       2137
#define IDB_RES_7                       2138
#define IDB_RES_8                       2139
#define IDB_RES_9                       2140
#define IDV_WIDTH                       2141
#define IDV_HEIGHT                      2142
#define IDV_X_OFFSET                    2143
#define IDV_Y_OFFSET                    2144
#define IDS_YMIN                        2145
#define IDS_XMIN                        2146
#define IDS_XRANGE                      2147
#define IDS_YRANGE                      2148
#define ID_SETROI                       2149
#define IDB_CENTER_CROSSHAIR            2150
#define IDB_RESET_GAINS_NEUTRAL         2151
#define IDT_PIXEL_INFO                  2152
#define IDB_RESET_0                     2153
#define IDB_RESET_1                     2154
#define IDB_RESET_2                     2155
#define IDB_RESET_3                     2156
#define IDB_RESET_4                     2157
#define IDB_RESET_5                     2158
#define IDB_RESET_6                     2159
#define IDB_RESET_7                     2160
#define IDB_RESET_8                     2161
#define IDB_RESET_9                     2162
#define IDT_CLASS_0                     2163
#define IDT_CLASS_1                     2164
#define IDT_CLASS_2                     2165
#define IDT_CLASS_3                     2166
#define IDT_CLASS_4                     2167
#define IDT_CLASS_5                     2168
#define IDT_CLASS_6                     2169
#define IDT_CLASS_7                     2170
#define IDT_CLASS_8                     2171
#define IDT_CLASS_9                     2172
#define IDT_MODEL_0                     2173
#define IDT_MODEL_1                     2174
#define IDT_MODEL_2                     2175
#define IDT_MODEL_3                     2176
#define IDT_MODEL_4                     2177
#define IDT_MODEL_5                     2178
#define IDT_MODEL_6                     2179
#define IDT_MODEL_7                     2180
#define IDT_MODEL_8                     2181
#define IDT_MODEL_9                     2182
#define IDB_OK                          2183
#define IDT_SERIAL_0                    2184
#define IDT_SERIAL_1                    2185
#define IDT_SERIAL_2                    2186
#define IDT_SERIAL_3                    2187
#define IDT_SERIAL_4                    2188
#define IDT_SERIAL_5                    2189
#define IDT_SERIAL_6                    2190
#define IDT_SERIAL_7                    2191
#define IDT_SERIAL_8                    2192
#define IDT_SERIAL_9                    2193
#define IDT_ID_0                        2194
#define IDT_ID_1                        2195
#define IDT_ID_2                        2196
#define IDT_ID_3                        2197
#define IDT_ID_4                        2198
#define IDT_ID_5                        2199
#define IDT_ID_6                        2200
#define IDT_ID_7                        2201
#define IDT_ID_8                        2202
#define IDT_ID_9                        2203
#define IDV_ALIAS_0                     2204
#define IDV_ALIAS_1                     2205
#define IDV_ALIAS_2                     2206
#define IDV_ALIAS_3                     2207
#define IDV_ALIAS_4                     2208
#define IDV_ALIAS_5                     2209
#define IDV_ALIAS_6                     2210
#define IDV_ALIAS_7                     2211
#define IDV_ALIAS_8                     2212
#define IDV_ALIAS_9                     2213
#define IDV_DESCRIPTION_0               2214
#define IDV_DESCRIPTION_1               2215
#define IDV_DESCRIPTION_2               2216
#define IDV_DESCRIPTION_3               2217
#define IDV_DESCRIPTION_4               2218
#define IDV_DESCRIPTION_5               2219
#define IDV_DESCRIPTION_6               2220
#define IDV_DESCRIPTION_7               2221
#define IDV_DESCRIPTION_8               2222
#define IDV_DESCRIPTION_9               2223
#define IDB_CLEAR_0                     2224
#define IDB_CLEAR_1                     2225
#define IDB_CLEAR_2                     2226
#define IDB_CLEAR_3                     2227
#define IDB_CLEAR_4                     2228
#define IDB_CLEAR_5                     2229
#define IDB_CLEAR_6                     2230
#define IDB_CLEAR_7                     2231
#define IDB_CLEAR_9                     2232
#define IDB_CLEAR_10                    2233
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2214
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
