//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ZooCam.rc
//
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDC_WINDOWSPROJECT1             109
#define IDR_MAINFRAME                   128
#define IDB_LOGO                        135
#define IDB_YELLOW_LED                  139
#define IDB_RED_LED                     140
#define IDB_GREEN_LED                   141
#define IDB_GRAY_LED                    142
#define IDV_CURRENT                     1000
#define IDV_VOLTAGE                     1001
#define IDB_CURRENT_ON                  1002
#define IDT_CURRENT                     1003
#define IDB_CURRENT_OFF                 1004
#define ID_LED                          1005
#define IDT_VOLTAGE                     1006
#define IDT_LEVELS                      1007
#define IDT_STATUS                      1009
#define IDB_SET_I                       1010
#define IDB_SET_V                       1011
#define IDC_CONNECT                     1015
#define IDC_B0                          1016
#define IDC_B1                          1017
#define IDC_B2                          1018
#define IDC_B3                          1019
#define IDC_B4                          1020
#define IDT_SRQ                         1021
#define IDB_STATUS_UPDATE               1022
#define IDC_STATUS_ON                   1023
#define IDB_SAVE                        1998
#define IDT_COMPILE_VERSION             1999
#define IDC_STATIC_ABOUT_COMPANY        2000
#define IDC_STATIC_ABOUT_APPNAME        2001
#define IDC_DISPLAY                     2003
#define IDB_LIVE                        2004
#define IDB_UNDOCK                      2005
#define IDB_FLOAT                       2005
#define IDB_CAPTURE                     2006
#define IDB_BURST                       2007
#define IDB_SAVE_PARAMETERS             2008
#define IDB_LOAD_PARAMETERS             2009
#define IDC_CAMERA_LIST                 2010
#define IDC_CAMERA_MODES                2011
#define IDB_CAMERA_DETAILS              2012
#define IDT_CAMERA_MANUFACTURER         2013
#define IDB_CAMERA_DISCONNECT           2013
#define IDT_CAMERA_MODEL                2014
#define IDT_CAMERA_SERIAL_NO            2015
#define IDT_CAMERA_ID                   2016
#define IDT_CAMERA_IMAGE_SIZE           2017
#define IDT_CAMERA_PIXEL_PITCH          2018
#define IDT_CAMERA_VERSION              2019
#define IDT_CAMERA_DATE                 2020
#define IDT_CAMERA_COLOR_MODE           2021
#define IDS_FRAME_RATE                  2022
#define IDT_PIXEL_CLOCK_MIN             2022
#define IDV_FRAME_RATE                  2023
#define IDT_PIXEL_CLOCK_DEFAULT         2023
#define IDT_FRAMERATE                   2024
#define IDT_PIXEL_CLOCK_CURRENT         2024
#define IDT_ACTUALFRAMERATE             2024
#define IDS_EXPOSURE_TIME               2025
#define IDT_PIXEL_CLOCK_MAX             2025
#define IDV_EXPOSURE_TIME               2026
#define IDT_PIXEL_CLOCK_INC             2026
#define IDS_GAMMA                       2027
#define IDT_CAMERA_NAME                 2027
#define IDV_GAMMA                       2028
#define IDB_GAMMA_NEUTRAL               2029
#define IDT_CAMERA_BIT_DEPTH            2029
#define IDR_COLOR_DISABLE               2030
#define IDR_COLOR_ENABLE                2031
#define IDR_COLOR_BG40                  2032
#define IDR_COLOR_HQ                    2033
#define IDR_COLOR_AUTO_IR               2034
#define IDV_COLOR_CORRECT_FACTOR        2035
#define IDG_VERT_PROFILE                2036
#define IDT_RED_SATURATE                2037
#define IDT_GREEN_SATURATE              2038
#define IDT_BLUE_SATURATE               2039
#define IDS_MASTER_GAIN                 2040
#define IDV_MASTER_GAIN                 2041
#define IDS_RED_GAIN                    2042
#define IDV_RED_GAIN                    2043
#define IDS_GREEN_GAIN                  2044
#define IDV_GREEN_GAIN                  2045
#define IDS_BLUE_GAIN                   2046
#define IDV_BLUE_GAIN                   2047
#define IDG_HORZ_PROFILE                2048
#define IDG_HISTOGRAMS                  2049
#define IDR_EXPOSURE_100US              2050
#define IDR_EXPOSURE_1MS                2051
#define IDR_EXPOSURE_10MS               2052
#define IDR_EXPOSURE_100MS              2053
#define IDT_MIN_EXPOSURE                2054
#define IDT_MID_EXPOSURE                2055
#define IDT_MAX_EXPOSURE                2056
#define IDB_RESET_CURSOR                2057
#define IDC_SHOW_INTENSITY              2058
#define IDC_SHOW_RGB                    2059
#define IDC_ENABLE_DCX_ERRORS           2060
#define IDC_FULL_WIDTH_CURSOR           2061
#define IDB_AUTO_EXPOSURE               2062
#define IDT_CURSOR_X_PIXEL              2063
#define IDT_CURSOR_Y_PIXEL              2064
#define IDV_RING_SIZE                   2065
#define IDT_FRAME_COUNT                 2066
#define IDT_FRAME_VALID                 2067
#define IDV_PIXEL_CLOCK_SET             2067
#define IDB_PIXEL_CLOCK_SET             2068
#define IDV_CURRENT_FRAME               2068
#define IDT_SHARPNESS                   2069
#define IDB_SHARPNESS_DIALOG            2070
#define IDB_LED_CONTROL                 2071
#define IDB_LED_CONFIGURE               2071
#define IDV_COM_PORT                    2072
#define IDC_TRACK_CENTROID              2072
#define IDC_ENABLE                      2073
#define IDV_LED_ON                      2074
#define IDV_LED_OFF                     2075
#define IDR_LED_OFF                     2076
#define IDR_LED_ON                      2077
#define IDR_LED_TOGGLE                  2078
#define IDG_FOCUS_GRAPH                 2079
#define IDR_TIME_SEQUENCE               2080
#define IDR_FOCUS_SWEEP                 2081
#define IDC_PAUSE                       2082
#define IDB_CLEAR_FOCUS_GRAPH           2083
#define IDT_EST_FOCUS                   2084
#define IDB_SET_EST_FOCUS               2085
#define IDB_ARM                         2086
#define IDB_PREV_FRAME                  2087
#define IDB_NEXT_FRAME                  2088
#define IDB_LED_OFF                     2091
#define IDB_LED_ON                      2092
#define IDG_LED                         2093
#define IDT_CAMERA_EXPOSE_MIN           2094
#define IDT_CAMERA_EXPOSE_MAX           2095
#define IDT_CAMERA_FPS_MIN              2096
#define IDT_CAMERA_FPS_MAX              2097
#define IDT_CAMERA_GAIN_MIN             2098
#define IDT_CAMERA_GAIN_MAX             2099
#define IDT_CAMERA_FIRMWARE             2100
#define IDG_COLOR_CORRECTION            2101
#define IDS_TEXT_0                      2102
#define IDC_SHOW_SUM                    2103
#define IDC_BUTTON1                     2104
#define IDB_RESET_GAINS                 2104
#define IDC_GPIB                        2401
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2105
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
